
import {Injectable}  from "@angular/core";
import {Mykitchen} from "./kitchenitems";
@Injectable({
    providedIn:'root'
})
export class KitchenService
{
    private kitchen:Mykitchen[]=[
        
{
    vegetableid:1,
    vegetablename:"potato",
    vegetablecost:30,
    vegetableimg:"./assets/images/potato.jpg"
  },
  {
    vegetableid:2,
    vegetablename:"Tomato",
    vegetablecost:40,
    vegetableimg:"./assets/images/tomato1.jpg"
  },
  {
    vegetableid:3,
    vegetablename:"Capsicum",
    vegetablecost:80,
    vegetableimg:"./assets/images/capsicum.jpg"
  },
  {
    vegetableid:4,
    vegetablename:"Brinjal",
    vegetablecost:50,
    vegetableimg:"./assets/images/brinjal.jpeg"
  },
  {
    vegetableid:5,
    vegetablename:"Apple",
    vegetablecost:120,
    vegetableimg:"./assets/images/apple.jpg"
  },
  {
    vegetableid:6,
    vegetablename:"Mango",
    vegetablecost:95,
    vegetableimg:"./assets/images/mango.jpg"
  },
  {
    vegetableid:7,
    vegetablename:"Banana",
    vegetablecost:40,
    vegetableimg:"./assets/images/banana.jpg"
  },
  {
    vegetableid:8,
    vegetablename:"Grapes",
    vegetablecost:60,
    vegetableimg:"./assets/images/grapes.jpg"
  },
  {
    vegetableid:9,
    vegetablename:"Kissmiss",
    vegetablecost:450,
    vegetableimg:"./assets/images/kissmiss.jpeg"
  },
  {
    vegetableid:10,
    vegetablename:"Kaaju",
    vegetablecost:980,
    vegetableimg:"./assets/images/kaaju.png"
  },
  {
    vegetableid:11,
    vegetablename:"Pista",
    vegetablecost:700,
    vegetableimg:"./assets/images/pista.jpeg"
  },
  {
    vegetableid:12,
    vegetablename:"Anjeer",
    vegetablecost:500,
    vegetableimg:"./assets/images/anjeer.jpeg"
  },
  {
    vegetableid:13,
    vegetablename:"Curd",
    vegetablecost:90,
    vegetableimg:"./assets/images/curd.png"
  },
  {
    vegetableid:14,
    vegetablename:"Butter",
    vegetablecost:600,
    vegetableimg:"./assets/images/butter.jpeg"
  },
  {
    vegetableid:15,
    vegetablename:"Cheese",
    vegetablecost:160,
    vegetableimg:"./assets/images/cheese.jpg"
  },
  {
    vegetableid:16,
    vegetablename:"Milk",
    vegetablecost:50,
    vegetableimg:"./assets/images/milk.png"
  },{
    vegetableid:17,
    vegetablename:"Eggs",
    vegetablecost:100,
    vegetableimg:"./assets/images/eggs.jpeg"
  },
  {
    vegetableid:18,
    vegetablename:"Rice",
    vegetablecost:70,
    vegetableimg:"./assets/images/rice.jpg"
  },
  {
    vegetableid:19,
    vegetablename:"Surf Excel",
    vegetablecost:100,
    vegetableimg:"./assets/images/surfexcel.png"
  },
  {
    vegetableid:20,
    vegetablename:"Cookies",
    vegetablecost:400,
    vegetableimg:"./assets/images/cookie.jpg"
  }
    ];
    getItems():Mykitchen[]
    {
        return this.kitchen;
    }
   
}

